### ISSUE TITLE
你好，请教一下：AccessToken是需要自己做缓存么？

### ISSUE THREAD

**Issue by fanatic-studio** [cute-angelia/bytedance-microapp#1]

**Comment by cute-angelia** [comment]
嗯， AccessToken 麻烦自己保存下

不过，一般场景用不到 AccessToken ， 登录场景也不需要 AccessToken

**Comment by cute-angelia** [comment]
@[fanatic-studio](https://github.com/fanatic-studio)

你要接什么需求？

**Comment by fanatic-studio** [comment]
qrcode

**Comment by fanatic-studio** [comment]
没事 我自己处理吧~

**Comment by fanatic-studio** [comment]
另外还有个问题请教下：你了解 视频挂载小程序能力么？ 我申请了下，被拒绝了，原因是：仅开放试点小程序

**Comment by cute-angelia** [comment]
@[fanatic-studio](https://github.com/fanatic-studio) 不清楚，可能只有它们指定的小程序才行
